# Generated by Django 5.1.6 on 2025-02-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_dislike_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
